lsi: false
safe: true
source: [https://github.com/celilreha/MNM-PHP-Symfony-Bootcamp]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
